homework_09/tsm_shop/shop/urls.py
from django.urls import path
from .views import (
    TSMIndexView,
    ProductListView,
    ProductCreateView,
    ProductDetailView,
)

app_name = "shop"

urlpatterns = [
    path("", TSMIndexView.as_view(), name="index"),
    path("products/", ProductListView.as_view(), name="products"),
    path("new_products/", ProductCreateView.as_view(), name="new_products"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product"),
]

homework_09/tsm_shop/site_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import LoginView, LogoutView, RegisterView

app_name = "site_auth"

urlpatterns = [
    path('me/', TemplateView.as_view(template_name="site_auth/me.html"),
         name="about-me"),
    path("login/", LoginView.as_view(),
         name="login"),
    path("logout/", LogoutView.as_view(),
         name="logout"),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
]

homework_09/tsm_shop/tsm_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", TemplateView.as_view(template_name="shop/index.html")),
    path('shop/', include('shop.urls')),
    path('auth/', include('site_auth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
    path('__debug__/', include('debug_toolbar.urls')),
    )

homework_09/tsm_shop/shop/models.py
from django.db import models
from django.contrib.auth.models import User as nickname

class User(models.Model):
    FirstName = models.CharField(max_length=100)
    LastName = models.CharField(max_length=100)

    def __str__(self):
        return f"User <{self.id}, {self.FirstName} {self.LastName}>"



class Product(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    added = models.ForeignKey(nickname, on_delete=models.CASCADE)

    def __str__(self):
        return f"Product <{self.pk}, {self.name!r}>"

homework_09/tsm_shop/site_auth/models.py
from django.db import models

# Create your models here.

homework_09/tsm_shop/shop/forms.py
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "added"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"
            if isinstance(field, forms.CharField):
                field.label
                print(field.label, type(field.label))

homework_09/tsm_shop/site_auth/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm as AuthenticationFormGeneric,
    UserCreationForm as UserCreationFormGeneric,
)
from django import forms
class AuthenticationForm(AuthenticationFormGeneric):
    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"

class UserCreationForm(UserCreationFormGeneric):
    class Meta(UserCreationFormGeneric.Meta):
        fields = "username", "email",

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"

homework_09/tsm_shop/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from .models import Product
from django.views.generic import TemplateView, ListView, CreateView, DetailView
from django.urls import reverse_lazy
from .forms import ProductForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
class TSMIndexView(TemplateView):
    template_name = "shop/index.html"


class ProductListView(LoginRequiredMixin, ListView):
    template_name = "shop/products.html"
    context_object_name = "products"
    queryset = Product.objects.order_by("id").select_related("added").all()


class ProductCreateView(CreateView):
    template_name = "shop/new_products.html"
#    model = Product
    form_class = ProductForm
#   fields = "name", "price", "description", "added"
    success_url = reverse_lazy("shop:products")

class ProductDetailView(DetailView):
#    template_name = "product_detail.html"
    model = Product

homework_09/tsm_shop/site_auth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogOutGeneric,
)
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import AuthenticationForm, UserCreationForm

class LoginView(LoginViewGeneric):
    template_name = "site_auth/login.html"
    form_class = AuthenticationForm
    next_page = reverse_lazy("site_auth:about-me")

class LogoutView(LogOutGeneric):
    next_page = reverse_lazy("site_auth:login")

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "site_auth/register.html"
    success_url = reverse_lazy("site_auth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        # user: AbstractUser = self.object
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user: AbstractUser = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response

homework_09/tsm_shop/shop/templates/shop/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
    Base
    {% endblock %}</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
<body>
<nav class="mb-2 px-3 navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'shop:index' %}">На главную</a>
    <div>
      {% if user.is_authenticated %}
        <a href="{% url 'site_auth:about-me' %}">{{ user.username }}</a>
        <a href="{% url 'site_auth:logout' %}">Logout</a>
      {% else %}
        <a
          class="btn btn-outline-primary"
          href="{% url 'site_auth:login' %}">
          Login
        </a>
      {% endif %}
    </div>
</nav>
  <div class="container">
{% block body %}

{% endblock %}
  </div>
</body>
</html>

homework_09/tsm_shop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block title %}
  TSM Shop Index
{% endblock %}

{% block body %}
  <h1>TopSuperMega Shop</h1>

  <div>
    <p>Links:</p>
    <ul>
      <li>
        <a href="{% url 'shop:products' %}">Получить конфиг</a>
      </li>
    </ul>
  </div>
{% endblock %}

homework_09/tsm_shop/shop/templates/shop/new_products.html
{% extends 'shop/base.html' %}

{% block title %}
  Новый конфиг
{% endblock %}

{% block body %}
 <h2>Добавить новый конфиг</h2>
 <form method="post">
   {% csrf_token %}
   {{ form.as_p }}

   <input class="btn btn-primary" type="submit" value="Create" >
 </form>
{% endblock %}

homework_09/tsm_shop/shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block title %}
  Конфиг #{{ product.pk }}
{% endblock %}

{% block body %}
 <h1>Подробнее о конфиге #{{ product.pk }}</h1>
 <h2><code>{{ product.name }}</code></h2>
 <h3>Описание</h3>
 <p>{{ product.description }}</p>

 <div>
     <a href="{% url 'shop:products' %}">Назад к списку продуктов</a>
 </div>
{% endblock %}

homework_09/tsm_shop/shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block title %}
  TSM Shop
{% endblock %}

{% block body %}
  <div>
      <h1>Products</h1>
      <ul>
          {% for product in products %}
          <li><a href="{% url "shop:product" pk=product.pk %}">{{product.name}}</a>
              <code> - {{product.price}}</code>
              - [{{ product.added }}]
          </li>
          {% endfor %}
      </ul>
  </div>
  <div>
    <ul>
      <li>
       <a href="{% url "shop:new_products" %}">Добавить новый конфиг</a>
      </li>

      <li>
       <a href="{% url "shop:index" %}">Назад на главную</a>
      </li>
    </ul>
  </div>
{% endblock %}

homework_09/tsm_shop/site_auth/templates/site_auth/login.html
{% extends 'shop/base.html' %}

{% block title %}
  Site login
{% endblock %}

{% block body %}
<!-- Pills content -->
<div class="tab-content">
  <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
    <form method="post">
      {% csrf_token %}

      {% if form.errors %}
         <p class="alert alert-danger">
           Something is not right
         </p>
      {% endif %}

      {{ form.as_p }}

      <input type="hidden" name="next" value="{{ next }}">
<!--      &lt;!&ndash; Email input &ndash;&gt;-->
<!--      <div class="form-outline mb-4">-->
<!--        <input type=text id="loginName" class="form-control" />-->
<!--        <label class="form-label" for="loginName">Username</label>-->
<!--      </div>-->

<!--      &lt;!&ndash; Password input &ndash;&gt;-->
<!--      <div class="form-outline mb-4">-->
<!--        <input type="password" id="loginPassword" class="form-control" />-->
<!--        <label class="form-label" for="loginPassword">Password</label>-->
<!--      </div>-->


      <!-- Submit button -->
      <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

      <!-- Register buttons -->
      <div class="text-left">
        <p>Not a member? <a href="{% url 'site_auth:register' %}">Register</a></p>
      </div>
    </form>
  </div>
  <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
    <form>

      <!-- Name input -->
      <div class="form-outline mb-4">
        <input type="text" id="registerName" class="form-control" />
        <label class="form-label" for="registerName">Name</label>
      </div>

      <!-- Username input -->
      <div class="form-outline mb-4">
        <input type="text" id="registerUsername" class="form-control" />
        <label class="form-label" for="registerUsername">Username</label>
      </div>

      <!-- Email input -->
      <div class="form-outline mb-4">
        <input type="email" id="registerEmail" class="form-control" />
        <label class="form-label" for="registerEmail">Email</label>
      </div>

      <!-- Password input -->
      <div class="form-outline mb-4">
        <input type="password" id="registerPassword" class="form-control" />
        <label class="form-label" for="registerPassword">Password</label>
      </div>

      <!-- Repeat Password input -->
      <div class="form-outline mb-4">
        <input type="password" id="registerRepeatPassword" class="form-control" />
        <label class="form-label" for="registerRepeatPassword">Repeat password</label>
      </div>

      <!-- Checkbox -->
      <div class="form-check d-flex justify-content-center mb-4">
        <input class="form-check-input me-2" type="checkbox" value="" id="registerCheck" checked
          aria-describedby="registerCheckHelpText" />
        <label class="form-check-label" for="registerCheck">
          I have read and agree to the terms
        </label>
      </div>

      <!-- Submit button -->
      <button type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
    </form>
  </div>
</div>
<!-- Pills content -->
{% endblock %}

homework_09/tsm_shop/site_auth/templates/site_auth/me.html
{% extends 'shop/base.html' %}

{% block title %}
  About Me
{% endblock %}

{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
     <p>Username: {{ user.username }}</p>
     <p>email: {{ user.email }}</p>
  {% else %}
    <h2>Anonymous user</h2>
  {% endif %}

{% endblock %}

homework_09/tsm_shop/site_auth/templates/site_auth/register.html
{% extends 'shop/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Register">
  </form>
{% endblock %}